language: minimal
services:
    - docker
stages:
  - name: deploy
    if: branch == main AND type = push
jobs:
  include:
    - stage: deploy
      script:
        - gcloud auth configure-docker us-west1-docker.pkg.dev
        - echo "$ARTIFACT_REGISTRY_KEY" | docker login -u _json_key_base64 --password-stdin https://us-west1-docker.pkg.dev
        - export REPO=us-west1-docker.pkg.dev/kcs-biarca-infra1/travis-sf/travis-image
        - docker build -f Dockerfile -t $REPO:build-$TRAVIS_BUILD_NUMBER -t $REPO:latest .
        - docker push $REPO:build-$TRAVIS_BUILD_NUMBER
        - docker push $REPO:latest
