# Dockerfile to create image with cron services
FROM ubuntu:latest

# Add the script to the Docker Image
ADD docker/log_cleaner.sh /root/log_cleaner.sh

# Give execution rights on the cron scripts
RUN chmod 777 /root/log_cleaner.sh
